name: feedback
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: 3.5.2
  flutter: 3.24.2

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shadcn_ui: ^0.9.5
  shared_preferences: ^2.3.2
  web: ^1.0.0
  
dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
