name: feedback
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: 3.10.1
  flutter: 3.38.3

dependencies:
  clock: ^1.1.1
  equatable: ^2.0.5
  feedback_client: 
    path: ../feedback_client
  fluentui_system_icons: ^1.1.257
  flutter:
    sdk: flutter
  gap: ^3.0.1
  intl:
  provider: ^6.1.2
  rxdart: ^0.27.5
  shadcn_ui: ^0.39.9
  stack_trace: ^1.11.1
  web: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
