name: feedback_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: 3.10.1
  flutter: 3.38.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  
dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
