api_platform:
    title: Feedback API
    version: 1.0.0
    mercure:
        enabled: false
        include_type: true
    formats:
        json: ["application/json"]
        jsonld: ["application/ld+json"]
        multipart: ["multipart/form-data"]
    docs_formats:
        jsonld: ["application/ld+json"]
        jsonopenapi: ["application/vnd.openapi+json"]
        html: ["text/html"]
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin", "X-AUTH-TOKEN"]
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
            
