name: feedback_pocketbase
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: 3.9.2
  flutter: 3.35.4
resolution: workspace

dependencies:
  feedback_client: 
    path: ../feedback_client
  flutter:
    sdk: flutter
  http: ^1.2.2
  pocketbase: ^0.18.1
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
