name: feedback_pocketbase
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  feedback_client: 
    path: ../feedback_client
  flutter:
    sdk: flutter
  http: ^1.6.0
  pocketbase: ^0.18.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
